'use strict';


module.exports = angular.module('uiComposer.uiCanvas', [])
    .controller('CanvasCtrl', require('./ui-canvas.controller.js'))
    .directive('npUiCanvasOverlay', require('./directives/np-ui-canvas-overlay/np-ui-canvas-overlay.directive.js'))
    .directive('npUiCanvasRuntime', require('./directives/np-ui-canvas-runtime/np-ui-canvas-runtime.directive.js'))
    .directive('npCanvasElementDelete', require('./directives/np-canvas-element-delete/np-canvas-element-delete.directive.js'))
    .directive('npCopyPaste', require('./directives/np-copy-paste/np-copy-paste.directive.js'))
    .directive('npMultiSelectDrag', require('./directives/np-multi-select-drag/np-multi-select-drag.directive.js'))
    .directive('npCanvasElementMove', require('./directives/np-canvas-element-move/np-canvas-element-move.directive.js'))
    .directive('npCanvasElementResizable', require('./directives/np-canvas-element-resizable/np-canvas-element-resizable.directive.js'))
    .directive('npCanvasElementSelect', require('./directives/np-canvas-element-select/np-canvas-element-select.directive.js'))
    .directive('npCanvasInteractionHandler', require('./directives/np-canvas-interaction-handler/np-canvas-interaction-handler.directive.js'))
    .directive('npCanvasInlineEdit', require('./directives/np-canvas-inline-edit/np-canvas-inline-edit.directive.js'))
    .directive('npCanvasScroll', require('./directives/np-canvas-scroll/np-canvas-scroll.directive.js'))
    .factory('npUiCanvasAPI', require('./services/np-ui-canvas-api/np-ui-canvas-api.service.js'))
    .factory('npBindingHelper', require('./services/np-binding-helper/np-binding-helper.service.js'))
    .factory('npGrid', require('./services/np-grid/np-grid.service.js'))
    .factory('npGridPosition', require('./services/np-grid/np-grid-position.service.js'))
    .factory('npCanvasUpdater', require('./services/np-canvas-updater/np-canvas-updater.service.js'))
    .factory('npCanvasEvents', require('./services/np-canvas-events/np-canvas-events.service.js'))
    .factory('npCanvasInteractionHelper', require('./services/np-canvas-interaction-helper/np-canvas-interaction-helper.service.js'))
    .factory('npCanvasInlineEditHelper', require('./services/np-canvas-inline-edit-helper/np-canvas-inline-edit-helper.service.js'))
    .factory('npCanvasElementDrop', require('./services/np-canvas-element-drop/np-canvas-element-drop.service.js'))
    .factory('npLayoutHelper', require('./services/np-layout-helper/np-layout-helper.service.js'))
    .factory('npSnapGuide', require('./services/np-snap-guide/np-snap-guide.service.js'))
    .factory('npCanvasElementHighlight', require('./services/np-canvas-element-highlight/np-canvas-element-highlight.service.js'));
