'use strict';

module.exports = angular.module('uiComposer.services', [])
    .factory('npKeyboarder', require('./np-keyboarder/np-keyboarder.service.js'))
    .factory('npKeyboarderHelper', require('./np-keyboarder/np-keyboarder-helper.service.js'))
    .factory('npMessaging', require('./np-messaging/np-messaging.service.js'))
    .factory('npPrototype', require('./np-prototype/np-prototype.service.js'))
    .factory('npEvents', require('./np-events/np-events.service.js'))
    .factory('npPageMetadata', require('./np-page-metadata/np-page-metadata.service.js'))
    .factory('npPageMetadataHelper', require('./np-page-metadata/np-page-metadata-helper.service.js'))
    .factory('npPageMetadataEvents', require('./np-page-metadata/np-page-metadata-events.service.js'))
    .factory('npPageMetadataAddControl', require('./np-page-metadata/np-page-metadata-add-control.service.js'))
    .factory('npPageMetadataCloneControl', require('./np-page-metadata/np-page-metadata-clone-control.service.js'))
    .factory('npPageMetadataDeleteControl', require('./np-page-metadata/np-page-metadata-delete-control.service.js'))
    .factory('npPageMetadataMoveControl', require('./np-page-metadata/np-page-metadata-move-control.service.js'))
    .factory('npPageMetadataChangeProperty', require('./np-page-metadata/np-page-metadata-change-property.service.js'))
    .factory('npPageMetadataControlBinding', require('./np-page-metadata/np-page-metadata-control-binding.service.js'))
    .factory('npPageMetadataMainEntity', require('./np-page-metadata/np-page-metadata-main-entity.service.js'))
    .factory('npPageMetadataChangeEvent', require('./np-page-metadata/np-page-metadata-change-event.service.js'))
    .factory('npImageHelper', require('./np-image-helper/np-image-helper.service.js'))
    .factory('npNavBarHelper', require('./np-navbar-helper/np-navbar-helper.service.js'))
    .factory('npUserInfo', require('./np-user-info/np-user-info.service.js'))
    .factory('npEnter', require('./np-enter/np-enter.service.js'))
    .factory('npPropertyChangeObserver', require('./np-property-change-observer/np-property-change-observer.service.js'))
    .factory('npConcurrentAccessHelper', require('./np-concurrent-access-helper/np-concurrent-access-helper.service.js'));
